# Generated by Django 6.0.5 on 2026-05-07 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='teacher',
        ),
        migrations.AddField(
            model_name='customuser',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='teachers', to=settings.AUTH_USER_MODEL, verbose_name='Закреплённые студенты'),
        ),
    ]
