# Generated by Django 6.0.5 on 2026-05-07 10:14

import courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название лекции')),
                ('content', models.TextField(blank=True, help_text='Текст лекции (можно использовать HTML)', verbose_name='Содержание')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo или другая платформа', verbose_name='Ссылка на видео')),
                ('file', models.FileField(blank=True, help_text='PDF, DOC, PPT и другие форматы', null=True, upload_to=courses.models.lecture_file_path, verbose_name='Файл лекции')),
                ('order', models.PositiveIntegerField(default=0, help_text='Для сортировки лекций', verbose_name='Порядковый номер')),
                ('duration', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Длительность (мин)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
                'ordering': ['course', 'order'],
            },
        ),
    ]
